## CONFIGS

# inference ply
ply: 0

# experiment configs 
num_iters: 1000
num_games_per_iter: 100

# training configs
epochs: 10
batch_size: 128

# pretraining configs
pretraining_epochs: 10
pretraining_batch_size: 2048

# model configs
embedding_dim: 64
num_layers: 8
