## CONFIGS

# inference ply
ply: 0

# experiment configs 
num_iters: 1000
num_games_per_iter: 2048

# training configs
epochs: 10
batch_size: 8192

# pretraining configs
pretraining_epochs: 100
pretraining_batch_size: 8192

# model configs
embedding_dim: 128
num_layers: 6
